name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'public/**', 'vite.config.js', 'package.json', '.github/workflows/deploy-frontend.yml' ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: aimcs-rg-eastus2
  STATIC_WEB_APP_NAME: aimcs-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci
      
    - name: Install frontend dependencies
      run: |
        cd src
        npm ci
        
    - name: Build frontend
      run: |
        cd src
        npm run build
        
    - name: Verify build output
      run: |
        ls -la src/dist/
        test -f src/dist/index.html || exit 1
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "src/dist"
        skip_app_build: true
        deployment_environment: production
        
    - name: Verify deployment
      run: |
        # Wait for deployment to complete
        sleep 30
        
        # Test the frontend endpoint
        curl -f https://aimcs.net || exit 1
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Frontend deployment successful!"
        else
          echo "❌ Frontend deployment failed!"
          exit 1
        fi 