name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r dist deploy/
          cp server.js deploy/
          cp package.json deploy/
          cp package-lock.json deploy/ || true

      - name: Zip artifact for deployment
        run: cd deploy && zip -r ../release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
          slot-name: 'production' 